name: mirror

on:
  push:
    branches-ignore:
     - 'ga-ignore-**'
  pull_request:
    branches-ignore:
     - 'ga-ignore-**'

env:
  MIRROR_URL: "MIRROR_URL_MIRROR_GENERATOR"
  EXECUTABLES: "EXECUTABLE_MIRROR_GENERATOR"

jobs:
  check_repository_cleanliness:
    name: Checks if the repository is clean and void of any unwanted files (temp files, binary files, etc.)
    runs-on: ubuntu-latest
    env:
      UNWANTED_REGEX: (.*\.gc(no|da|ov))$|(.*\.(a|o|so))$|(.*~)$|^(#.*#)$|(.*(?i)pain_au_chocolat.*)|^tmp\/.*|.*\/tmp\/.*
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find temp files in all directories
        run: |
          UNWANTED_FILES=$(find . -type f -printf '%P\n' | { grep -P "${{ env.UNWANTED_REGEX }}" || true; })
          if [ "$UNWANTED_FILES" != "" ]; then
              IFS=$'\n'$'\r'
              for LINE in $UNWANTED_FILES; do
                  echo "::error file=${LINE},line=1,col=1,title=Unwanted file detected::${LINE}"
              done
              echo "FAIL_TASK=true" >> "$GITHUB_ENV"
          else
              echo "FAIL_TASK=false" >> "$GITHUB_ENV"
          fi

      - name: Fail if needed
        if: env.FAIL_TASK == 'true'
        run: exit 1

  check_program_compilation:
    name: Checks if the program compiles correctly and executables files got created
    runs-on: ubuntu-latest
    needs: [check_repository_cleanliness]
    container: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: make
        timeout-minutes: 2

      - run: make clean

      - name: Verifies that files are present and executable
        run: |
          echo "FAIL_TASK=false" >> "$GITHUB_ENV"
          SEARCH_BINARIES="${{ env.EXECUTABLES }}"
          IFS=$','
          for BIN in $SEARCH_BINARIES; do
              if [ ! -f "${BIN}" ]; then
                  echo "::error file=${BIN},title=Binary not found::${BIN}"
                  echo "FAIL_TASK=true" >> "$GITHUB_ENV"
              fi
              if [ ! -x "${BIN}" ]; then
                  echo "::error file=${BIN},title=Binary not executable::${BIN}"
                  echo "FAIL_TASK=true" >> "$GITHUB_ENV"
              fi
          done

      - name: Fail if needed
        if: env.FAIL_TASK == 'true'
        run: exit 1

      - name: Starts tests
        run: make tests_run
        timeout-minutes: 2

  push_to_mirror:
    name: Pushes the current repository files to a given mirror repository
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs: [check_program_compilation]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
