name: Feature Request
description: Suggest an idea for this project
title: "[feature name] <title>"
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you are requesting
      placeholder: Describe the feature you are requesting
      render: markdown
  - type: textarea
    id: feature-test-cases
    attributes:
      label: Test Cases
      description: Describe the test cases to do to prove that the feature works
      placeholder: Describe the test cases to do to prove that the feature works
      render: markdown
  - type: textarea
    id: little-code-snipet
    attributes:
      label: Little Code Snippet
      description: If you have a little code snippet that can help to implement the feature, please add it here (don't forget to modify the language of the snippet if needed)
      placeholder: If you have a little code snippet that can help to implement the feature, please add it here
      render: markdown
  
