# Created by @Miou-zora (please keep it ;) )

name: mirror

on: [push]

jobs:
  dependencies:
    name: Check dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          make install

  tests:
    name: Launch tests
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Launch tests
        run:
          make tests_run
  
  coding-style:
    name: Check coding style
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          make install
      
      - name: Check coding style
        run:
          make check_style

