# Created by @Miou-zora (please keep it ;) )

name: mirror

on: [push]

jobs:
  tests:
    name: Launch tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Dependencies
        run: |
          make install

      - name: Check coding style
        run:
          make coding_style_details

      - name: Launch tests
        run:
          make tests_run

